language: node_js

node_js:
  - '8'

before_install:
  - 'npm install -g npm@latest'

notifications:
  email: false

dependencies:
  - post
    - npm run bootstrap

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.9