language: node_js

node_js:
  - '8'

before_install:
  - 'npm install -g npm@latest'

install:
  - npm install
  - ./node_modules/.bin/lerna bootstrap --hoist --ci

notifications:
  email: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.9